### PR TITLE
Enumerable Tests

### PR DESCRIPTION
**Pull request by rayking12**
Enumerable methods testing using Rspec 
things to look out for:
Rspec tests for each enumerable  method

### CODE REVIEW

**Review by Spayco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [x] Pull Request should have a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

## Optional 🟢 

- [ ] add a testing section in your README.md

- [ ] add RSpec to your GemFile

- [ ] I noticed that you're using `#each` to create `#my_each`, that's not a proper way of making your own method, if you use the method that you're trying to replicate, try to redo those methods, without relying on `#each`, you're here to learn, bypassing this might sound good for now, but when you face such things in a job/personal project, you will get stuck, so it's for your own good to fix these methods

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by rayking12** [comment]
Things to look out for:
Rspecs Testing of each method in the enumerable project

**Review by Spayco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] please update the post with a brief description instead of commenting ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

## Optional 🟢

- [ ]  add a testing section in your README.md

- [ ]  add RSpec to your GemFile

- [ ]  I noticed that you're using #each to create #my_each, that's not a proper way of making your own method, if you use the method that you're trying to replicate, try to redo those methods, without relying on #each, you're here to learn, bypassing this might sound good for now, but when you face such things in a job/personal project, you will get stuck, so it's for your own good to fix these methods

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by blackpintz — APPROVED** [review]
# Status: Approved 🎉 

**Congratulations team and good luck with your next project 😄.**

**Pull request closed without merging**
